const icon = (path: string) => `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${path}</svg>`
const page = icon('<path d="M14 3H6a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9Z"/><path d="M14 3v6h6M8 13h8M8 17h5"/>')
const layers = icon('<path d="m12 3 10 5-10 5L2 8Z"/><path d="m2 12 10 5 10-5M2 16l10 5 10-5"/>')
const team = icon('<circle cx="9" cy="8" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3M16 5a3 3 0 0 1 0 6M18 14a5 5 0 0 1 3 5v2"/>')
const cloud = icon('<path d="M7 18a5 5 0 1 1 1-10 6 6 0 0 1 11 3 3.5 3.5 0 0 1-1 7Z"/>')

export function landingPage(version: string, about = false, content?: { title: string; description: string; body: string }): string {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${content ? content.title : about ? 'About | BizzCMS' : 'BizzCMS - Content management, built for Cloudflare'}</title><meta name="description" content="${content ? content.description : 'An open-source CMS for business websites. Pages, posts and structured content, built on Cloudflare Workers and D1.'}"><link rel="icon" href="/brand/bizzcms.svg" type="image/svg+xml"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="/brand/landing.css"></head><body>
  <header class="shell"><a class="brand" href="/"><img src="/brand/bizzcms.svg" alt="" width="36" height="40">BizzCMS <span>OPEN SOURCE</span></a><nav aria-label="Main navigation"><a href="/#foundation">Cloudflare</a><a href="/blog">Blog</a><a href="/about">About</a><a class="nav-admin" href="/admin">Open CMS <span aria-hidden="true">↗</span></a></nav></header>
  <main class="shell">${content ? content.body : about ? `<section class="about"><p class="eyebrow">OPEN SOURCE. YOURS TO BUILD ON.</p><h1>Your content.<br><em>Your CMS.</em></h1><p class="intro">Lightweight content management for business websites.</p><h2>A foundation you can make your own.</h2><p>BizzCMS is MIT licensed; the notices for the open-source components it uses live in the repository.</p><h2>Cloudflare first.</h2><p>Workers runs the application, D1 holds its content, and R2 is the intended media store. The local preview uses Wrangler emulation. Production deployment and end-to-end media verification are still ahead.</p><p>Version ${version} is an early development release. Pages, posts and the admin are available locally. Independent Node.js hosting and generic S3 compatibility remain roadmap work.</p><div class="actions"><a class="button primary" href="/admin">Explore the CMS <span>↗</span></a><a class="text-link" href="https://github.com/BizzCMS/bizzcms">View the source ↗</a></div></section>` : `
  <section class="hero"><div><p class="eyebrow"><span class="dot"></span> OPEN SOURCE. YOURS TO BUILD ON.</p><h1>A lighter home<br>for your <em>content.</em></h1><p class="intro">A simple workspace for the pages, posts and people behind your business website. Built for Cloudflare, with room to make it your own.</p><div class="actions"><a class="button primary" href="/admin">Explore the CMS <span>↗</span></a><a class="text-link" href="https://github.com/BizzCMS/bizzcms">View the source ↗</a></div><p class="release">MIT licensed <span>·</span> v${version} <span>·</span> Local preview</p></div>
  <div class="workspace"><div class="workspace-top"><span class="mini-mark">${layers}</span>Your content workspace<span class="workspace-dots">•••</span></div><div class="workspace-body"><p class="eyebrow">LESS FRICTION. MORE CREATING.</p><h2>Everything in<br>its right place.</h2><div class="workspace-row"><span class="tile">${page}</span><div><strong>Pages &amp; posts</strong><small>From your first draft to the final word.</small></div><span>↗</span></div><div class="workspace-row"><span class="tile">${layers}</span><div><strong>Structured collections</strong><small>A clear home for every kind of content.</small></div><span>↗</span></div><div class="workspace-row"><span class="tile">${team}</span><div><strong>Your team, together</strong><small>One workspace. The right permissions.</small></div><span>↗</span></div></div><a class="cloud-strip" href="#foundation">${cloud}<span><strong>A Cloudflare foundation</strong><small>Workers runtime · D1 database</small></span><span>↓</span></a></div></section>
  <section class="features" aria-label="What you can do"><article><span class="feature-icon">${page}</span><h2>Create. Refine. Publish.</h2><p>Write pages and posts with a rich-text editor, drafts and structured fields that keep your content organised.</p></article><article><span class="feature-icon">${team}</span><h2>A place for your team.</h2><p>Manage users and permissions in the same workspace as your content. Keep everyday tasks within reach.</p></article><article><span class="feature-icon">${layers}</span><h2>Open from the start.</h2><p>MIT-licensed source, written in TypeScript. Explore it, adapt it and build on a foundation you own.</p></article></section>
  <section class="foundation" id="foundation"><div class="foundation-heading"><div><p class="eyebrow">${cloud} BUILT FOR CLOUDFLARE</p><h2>A lighter CMS.<br>A capable foundation.</h2></div><p>Cloudflare is central to the architecture. Your application, content and media each have a clear place to live.</p></div><div class="stack"><article><span>01 / APPLICATION</span><h3>Workers</h3><p>The runtime for BizzCMS, without a traditional application server to maintain.</p><a href="https://developers.cloudflare.com/workers/">Explore Workers ↗</a></article><article><span>02 / CONTENT</span><h3>D1</h3><p>A managed SQL database for your collections, pages and application records.</p><a href="https://developers.cloudflare.com/d1/">Explore D1 ↗</a></article><article><span>03 / MEDIA</span><h3>R2</h3><p>The intended home for uploaded images and files, separate from the application.</p><a href="https://developers.cloudflare.com/r2/">Explore R2 ↗</a></article></div><p class="foundation-note">This preview runs on local Cloudflare emulation. Production deployment and end-to-end media verification are still ahead.</p></section>
  <section class="next-step"><div><p class="eyebrow">A CLEAR START. ROOM TO GROW.</p><h2>Start with content.<br>Build from there.</h2></div><div><p>Pages, posts, the editor and admin are ready to explore locally. Independent Node.js hosting, S3 compatibility and a streamlined production setup remain on the roadmap.</p><a class="text-link" href="/about">Get to know BizzCMS <span>↗</span></a></div></section>`}</main>
  <footer class="shell"><span>© ${new Date().getFullYear()} BizzCMS · v${version} <a class="maker" href="https://ingenium.software/">Made by Ingenium ↗</a></span><span><a href="https://github.com/BizzCMS/bizzcms">GitHub ↗</a><a href="https://bizzcms.com">bizzcms.com</a><a href="/about">About</a></span></footer></body></html>`
}
